print("enter dsleep in 3 sec, wake up after 60 sec")
tmr.alarm(tmr_pwr, 3000, 0, function()
	print("finalize perifs")
	tmr.stop(tmr_com)
	tmr.stop(tmr_wifi)
	tmr.stop(tmr_led)
	tmr.stop(tmr_but)
	print("dsleep")
	node.dsleep(60000000)
end)
